AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SSHKeyNameParameter:
    Description: SSH key name
    Type: String

  SSHPublicKeyValueParameter:
    Description: SSH keypair to login
    Type: String
    NoEcho: true

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-066784287e358dad1
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref SecurityGroup
      KeyName: !Ref KeyPair
      UserData: !Base64 |
        #!/bin/bash
        sudo yum -y update
        sudo yum -y install nginx  
        sudo systemctl start nginx
        sudo systemctl enable nginx
        sudo chmod 755 /usr/share/nginx/html
        sudo curl -o  /usr/share/nginx/html/cat.jpg "https://as1.ftcdn.net/v2/jpg/02/36/99/22/1000_F_236992283_sNOxCVQeFLd5pdqaKGh8DRGMZy7P4XKm.jpg"
        echo "<h2> Ready </h2>" | sudo tee /usr/share/nginx/html/index.html 
        echo "<img src="cat.jpg" alt="Cat">" | sudo tee -a  /usr/share/nginx/html/index.html

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable traffic
      GroupName: cloudfrontSG
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22

        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80

        - CidrIp: 185.53.133.78/32
          FromPort: -1
          IpProtocol: icmp
          ToPort: -1

  KeyParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub "/CF/${SSHKeyNameParameter}"
      Value: !Ref SSHPublicKeyValueParameter

  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyType: rsa
      KeyName: !Ref SSHKeyNameParameter
      PublicKeyMaterial: !Ref SSHPublicKeyValueParameter
